{% set name = "tune-sklearn" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # NOTE: pypi doesnt contain a source package for it. See
  # https://github.com/ray-project/tune-sklearn/issues/159
  url: https://github.com/ray-project/tune-sklearn/archive/v{{ version }}.tar.gz
  sha256: 6779cf4c6edb1603b77c010a4b2070ef6757a31064a33cab4ab9357517e660f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - ray-tune >=1.0.1
    - ray-core >=1.0.1
    - pandas
    - numpy >=1.16
    - scipy
    - scikit-learn >=0.23
    - scikit-optimize

test:
  imports:
    - tune_sklearn

about:
  home: https://github.com/ray-project/tune-sklearn
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A drop-in replacement for Scikit-Learn’s GridSearchCV / RandomizedSearchCV -- but with cutting edge hyperparameter tuning techniques.

extra:
  recipe-maintainers:
    - hadim
